export {default as Invoices} from './Invoices/Invoices.tsx'
export {default as Loans} from './Loans/Loans.tsx'
export {default as Profile} from './Profile/Profile.tsx'
export {default as Referrals} from './Referrals/Referrals.tsx'
export {default as Settings} from './Settings/Settings.tsx'
export {default as Summary} from './Summary/Summary.tsx'